// ── Hooks — Point d'entrée centralisé ────────────────────────
export { useSupabaseData, useSupabaseMutation } from './useData'
export { usePartenairesPublic, usePartenaireProfil, useAllPartenaires } from './usePartenaires'
export { useRdvClient, useRdvPartenaire, useRdvEmploye, useAllRdv, useCreateRdv, useUpdateRdvStatut, useCancelRdv } from './useRendezvous'
export { useServicesPublic, useAllServices } from './useServices'
export { useArticles, useArticle } from './useArticles'
export { usePlans, useAbonnementClient, useAllAbonnements, useCreateAbonnement, useCancelAbonnement, useUpsertPlan } from './useAbonnements'
export { useCandidature, useAllCandidatures, useFormationModules, useFormationProgression, useSubmitCandidature, useUpdateCandidatureStatut, useCompleteModule, useFormationPartenaire, useFormationFournisseur } from './useCandidatures'
export { useChaises, useChaisesAdmin, useReservationsPartenaire, useReservationsJour, useCreateReservation, useCancelReservation } from './useChaises'
export { useClientProfil, useAllClients, useCreateClient, useUpdateClient } from './useClients'
export { useEmployeProfil, useAllEmployes, useUpsertEmploye } from './useEmployes'
export { useFournisseurProfil, useProduitsFournisseur, useAllProduits, useCommandesPartenaire, useCommandesFournisseur, useCreateCommande, useUpsertProduit } from './useFournisseurs'
export { useTransactionsPartenaire, useSoldePartenaire, useBonusConversions, useAllTransactions } from './usePortefeuille'
export { useSalonConfig, useFraisDeplacement, useSmsLogs, useUpdateSalonConfig } from './useSalon'
export { useAuth, useRequireAuth } from './useAuth'
