export const RECOMPENSES_MENSUELLES = [
  {
    id: 'excellence',
    label: 'Excellence client',
    desc: 'Note moyenne ≥ 4.8 sur le mois',
    bonus: 50,
    icon: '⭐',
    couleur: '#B8922A',
    objectif_label: 'Note moy.',
    objectif_key: 'note_moyenne_mois',
    objectif_cible: 4.8,
  },
  {
    id: 'fiabilite',
    label: 'Zéro no-show',
    desc: 'Aucun no-show sur le mois',
    bonus: 25,
    icon: '✅',
    couleur: '#22c55e',
    objectif_label: 'No-shows',
    objectif_key: 'no_shows_mois',
    objectif_cible: 0,
  },
  {
    id: 'mvp',
    label: 'MVP du mois',
    desc: '20+ services sur le mois',
    bonus: 75,
    icon: '🏆',
    couleur: '#f59e0b',
    objectif_label: 'Services',
    objectif_key: 'services_mois',
    objectif_cible: 20,
  },
  {
    id: 'acquisition',
    label: 'Acquisition client',
    desc: '5+ nouveaux clients dans le mois',
    bonus: 30,
    icon: '🎯',
    couleur: '#60a5fa',
    objectif_label: 'Nouveaux clients',
    objectif_key: 'nouveaux_clients_mois',
    objectif_cible: 5,
  },
]
